### PR TITLE
Support .msix packages

### PR DESCRIPTION
**Pull request by lowdesertpunk**
This commit is a cherry-pick of https://github.com/microsoft/StoreBroker/commit/cf2379a8b6e60032f6c1fd1cd17ae27bd7b2318f coming from the PR https://github.com/microsoft/StoreBroker/pull/163

Function names and documentation is not updated to keep the diff as short as possible.

Also hoping that this change will be deprecated by the official StoreBroker v2 soon.

### CODE REVIEW

**Review by palver123 — CHANGES_REQUESTED** [review]
I think ~~line 2170 was missed~~ _the string formatting in line 2170 should be changed too_, see [original diff](https://github.com/microsoft/StoreBroker/pull/163/files#diff-559f25e282d9dc595840c5026f46d6ecR1770).

**Comment by lowdesertpunk** [comment]
No, that's a variable rename which wasn't cherry-picked.

**Comment by lowdesertpunk** [comment]
Actually it's not even part of the diff you linked.

**Comment by lowdesertpunk** [comment]
Got it now (was a confusing comment) it's not the line 2170 from the diff which is missing.

**Comment by lowdesertpunk** [comment]
Changed the mentioned line (worked without it, as it's only an error message modification, I was hesitant changing them as well, to further shorten the changeset)

**Review by palver123 — APPROVED** [review]

**Pull request merged**
